server:
  port: 18082
spring:
  application:
    name: "spring-boot-jpa"
  cache:
    type: redis
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  datasource:
    url: jdbc:mysql://localhost:13306/local?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Hongkong
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      minimum-idle: 1
      maximum-pool-size: 10
  data:
    mongodb:
      uri: mongodb://jia:123456@127.0.0.1:27017/mongo
  redis:
    host: 127.0.0.1
    port: 6379
    password: jinpeng-mini-redis
    database: 0
    timeout: 3000
    connect-timeout: 3000
    lettuce:
      pool:
        max-active: 8   # 连接池最大连接数（使用负值表示没有限制） 默认 8
        max-wait: -1    # 连接池最大阻塞等待时间（使用负值表示没有限制） 默认 -1
        max-idle: 8     # 连接池中的最大空闲连接 默认 8
        min-idle: 2     # 连接池中的最小空闲连接 默认 0
    redisson:
      config: |
        singleServerConfig:
          address: redis://127.0.0.1:6379
          password: jinpeng-mini-redis
          database: 0
        threads: 0
        nettyThreads: 0
        transportMode: "NIO"
  minio:
    endpoint: "http://127.0.0.1:9000"
    accessKey: root
    secretKey: jinpeng123
    bucket: dev

